version: '3.8'

services:
  music-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - ./music_library:/app/music_library
    env_file:
      - .env